#设置服务器的端口号
servser:
  port:8080
#数据库连接设置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sport?userSSL=false&serverTimezone=GMT
    username: root
    password: gaoyue123
    type: com.alibaba.druid.pool.DruidDataSource
