
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/movement?serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: gaoyue159
    port: 25
    protocol: smtp
    username: 13949033311@163.com

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qfedu.sport.domain

logging:
  level:
    com:
      qfedu:
        sport:
          dao: debug

